[package]
name = "diagnostic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lockfree-object-pool = { workspace = true }
miette = { workspace = true }
smallvec = { workspace = true }

[package.metadata.release]
release = false
